version: 2.1

orbs:
  docker: circleci/docker@2.8.2

jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run:
          name: Build
          command: echo "Building the project"

  test:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run:
          name: Test
          command: echo "Running tests"

  build-docker-image:
    docker:
      - image: cimg/base:2023.03
    steps:
      - setup_remote_docker
      - checkout
      - docker/build:
          image: my_repo/my_image
          tag: latest
      - docker/push:
          image: my_repo/my_image
          tag: latest

workflows:
  build_test_and_docker:
    jobs:
      - build
      - test:
          requires:
            - build
      - build-docker-image:
          requires:
            - test